config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  resources :users, only: [:update, :show, :index]

  resources :topics do
    resources :posts, except: [:index ], controller: 'topics/posts'
  end

  resources :posts, only: [:index] do
    resources :comments, only: [:create, :destroy]
    resources :favorites, only: [:create, :destroy]
    post '/up-vote' => 'votes#up_vote', as: :up_vote
    post '/down-vote' => 'votes#down_vote', as: :down_vote
  end

  get 'about' => 'welcome#about'

  root to: 'welcome#index'
end

app/models/post.rb
class Post < ActiveRecord::Base
  has_many :comments, dependent: :destroy
  has_many :votes, dependent: :destroy
  has_many :favorites, dependent: :destroy
  belongs_to :user
  belongs_to :topic
  scope :visible_to, ->(user) { user ? all : joins(:topic).where('topics.public' => true) }
  mount_uploader :image, ImageUploader
  validates :title, length: { minimum: 5 }, presence: true
  validates :body, length: { minimum: 20 }, presence: true
  validates :topic, presence: true
  validates :user, presence: true

  def up_votes
    votes.where(value: 1).count
  end

  def down_votes
    votes.where(value: -1).count
  end

  def points
    votes.sum(:value)
  end

  def update_rank
    age_in_days = (created_at - Time.new(1970,1,1)) / (60 * 60 * 24)
    new_rank = points + age_in_days

    update_attribute(:rank, new_rank)
  end

  default_scope { order('rank DESC') }

  def create_vote
    user.votes.create(value: 1, post: self)
  end

  def save_with_initial_vote
    ActiveRecord::Base.transaction do
      save!
      create_vote if self.votes.count.zero?
    end
  rescue ActiveRecord::RecordInvalid
  end

end

app/models/topic.rb
class Topic < ActiveRecord::Base
  has_many :posts, dependent: :destroy

  scope :publicly_viewable, -> { where(public: true) }
  scope :privately_viewable, -> { where(public: false) }
  scope :visible_to, -> (user) { user ? all : publicly_viewable }
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @posts = Post.visible_to(current_user).where("posts.created_at > ?", 7.days.ago).paginate(page: params[:page], per_page: 10)
  end
end

app/controllers/topics/posts_controller.rb
class Topics::PostsController < ApplicationController

  def show
    @post = Post.find(params[:id])
    @topic = Topic.find(params[:topic_id])
    @comments = @post.comments.order(created_at: :desc)
    authorize @topic
  end

  def new
    @topic = Topic.find(params[:topic_id])
    @post = Post.new
    authorize @post
  end

  def create
    @topic = Topic.find(params[:topic_id])
    @post = current_user.posts.build(post_params)
    @post.topic = @topic
    authorize @post

    if @post.save_with_initial_vote
      flash[:notice] = "Post was saved."
      redirect_to [@topic, @post]
    else
      flash[:error] = "There was an error saving the post. Please try again."
      render :new
    end
  end

  def edit
    @topic = Topic.find(params[:topic_id])
    @post = Post.find(params[:id])
    authorize @post
  end

  def update
    @topic = Topic.find(params[:topic_id])
    @post = Post.find(params[:id])
    authorize @post
    if @post.update_attributes(post_params)
      flash[:notice] = "Post was updated."
      redirect_to [@topic, @post]
    else
      flash[:error] = "There was an error saving the post. Please try again."
      render :edit
    end
  end

  def destroy
    @topic = Topic.find(params[:topic_id])
    @post = Post.find(params[:id])
    title = @post.title
    authorize @post

    if @post.destroy
      flash[:notice] = "\"#{title}\" was deleted successfully."
      redirect_to @topic
    else
      flash[:error] = "There was an error deleting the post. Please try again."
      render :show
    end
  end

  private

  def post_params
    params.require(:post).permit(:title, :body, :image)
  end

end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
  def index
    @topics = Topic.visible_to(current_user).paginate(page: params[:page], per_page: 10)
    authorize @topics
  end

  def new
    @topic = Topic.new
    authorize @topic
  end

  def show
    @topic = Topic.find(params[:id])
    @posts = @topic.posts.includes(:user).paginate(page: params[:page], per_page: 10)
    authorize @topic
  end

  def edit
    @topic = Topic.find(params[:id])
    authorize @topic
  end

  def create
    @topic = Topic.new(topic_params)
    authorize @topic
    if @topic.save
      redirect_to @topic, notice: "Topic was saved successfully."
    else
      flash[:error] = "Error creating topic. Please try again."
      render :new
    end
  end

  def update
    @topic = Topic.find(params[:id])
    authorize @topic
    if @topic.update_attributes(topic_params)
      redirect_to @topic
    else
      flash[:error] = "Error saving topic. Please try again."
      render :edit
    end
  end

  def destroy
    @topic = Topic.find(params[:id])
    name = @topic.name

    authorize @topic
    if @topic.destroy
      redirect_to topics_path, notice: "\"#{name}\" was deleted successfully."
    else
      flash[:error] = "Error deleting topic. Please try again."
      render :show
    end
  end

  private

  def topic_params
    params.require(:topic).permit(:name, :description, :public)
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/views/topics/posts/_form.html.erb
<%= simple_form_for [topic, post] do |f| %>
  <%= f.input :title, label: 'Title', placeholder: "Enter post title" %>
  <% if post.image? %>
    <div class="form-group">
      <label>Current Image</label>
      <br>
      <%= image_tag( post.image.url ) %>
    </div>
  <% end %>
  <div class="form-group">
    <%= f.label :image %>
    <%= f.file_field :image %>
    <%= f.hidden_field :image_cache %>
  </div>
  <br/>
  <%= f.input :body, label: 'Body', placeholder: "Enter post body", :input_html => { 'rows' => 8 }  %>
  <%= f.submit 'Save' , class: 'btn btn-success' %>
<% end %>

app/views/topics/posts/edit.html.erb
 <h1>Edit Post</h1>

 <div class="row">
   <div class="col-md-4">
     <p>Guidelines for posts</p>
     <ul>
       <li>Make sure the it rhymes.</li>
       <li>Don't use the letter "A".</li>
       <li>The incessant use of hashtags will get you banned.</li>
     </ul>
   </div>
   <div class="col-md-8">
    <%= render partial: 'form', locals: { topic: @topic, post: @post } %>
   </div>
 </div>

app/views/topics/posts/new.html.erb
 <h1>New Post</h1>

 <div class="row">
   <div class="col-md-4">
     <p>Guidelines for posts</p>
     <ul>
       <li>Make sure the it rhymes.</li>
       <li>Don't use the letter "A".</li>
       <li>The incessant use of hashtags will get you banned.</li>
     </ul>
   </div>
   <div class="col-md-8">
    <%= render partial: 'form', locals: { topic: @topic, post: @post } %>
   </div>
 </div>

app/views/topics/posts/show.html.erb
<%= image_tag(@post.image.url) if @post.image? %>
<div class="row">
  <div class="col-md-8">
    <h1><%= markdown @post.title %></h1>
    <%= render partial: 'votes/voter', locals: { post: @post } %>
    <%= image_tag(@post.user.avatar.tiny.url) if @post.user.avatar? %>
    <small>submitted <%= time_ago_in_words(@post.created_at) %> ago by <%= @post.user.name %></small>
    <p><%= markdown @post.body %></p>
    <% if policy(@post).edit? %>
      <%= link_to "Edit", edit_topic_post_path(@topic, @post), class: 'btn btn-success' %>
    <% end %>
    <% if policy(@post).destroy? %>
      <%= link_to "Delete Post", [@topic, @post], method: :delete, class: 'btn btn-danger', data: { confirm: 'Are you sure you want to delete this post?'} %>
    <% end %>
    <div>
      <h3><%= pluralize(@post.points, 'point') %></h3>
      <small>
        <%= pluralize(@post.up_votes, 'up vote') %> |
        <%= pluralize(@post.down_votes, 'down vote') %>
      </small>
    </div>
    <%= render partial: 'favorites/favorite', locals: { post: @post } %>
  </div>
</div>
<br>
<div class="row">
  <div class="col-lg-12">
    <h1>Comments</h1>
  </div>
</div>
<div class="new-comment">
  <% if user_signed_in? %>
      <%= render partial: 'comments/form' %>
  <% end %>
</div>
<div class="js-comments">
  <%= render partial: 'comments/comment'%>
</div>